[project]
name = "jokes-python"
version = "0.1.0"
description = "Jokes server, in python, for learning MCP"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.13.0",
    "pydantic>=2.11.7",
]
